# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredefinedConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('required_bytes', models.BigIntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('cfg_file', models.FileField(upload_to='predefined_configurations', verbose_name='configuration file')),
            ],
        ),
    ]
