# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubmitExperiment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predefinedconfigurations',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
