# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubmitExperiment', '0002_accesscode'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscode',
            name='description',
            field=models.CharField(default='default', max_length=150),
            preserve_default=False,
        ),
    ]
