# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SubmitExperiment', '0002_auto_20170321_1805'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PredefinedConfigurations',
            new_name='PredefinedConfiguration',
        ),
    ]
