# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubmitExperiment', '0003_auto_20170321_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predefinedconfiguration',
            name='required_bytes',
            field=models.BigIntegerField(),
        ),
    ]
