# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 18:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SubmitExperiment', '0005_auto_20170321_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predefinedconfiguration',
            old_name='Configuration file',
            new_name='cfg_file',
        ),
    ]
