# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubmitExperiment', '0006_auto_20170321_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predefinedconfiguration',
            name='cfg_file',
            field=models.FileField(upload_to='predefined_configurations', verbose_name='configuration file'),
        ),
    ]
